/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SessionSessionIdRouteImport } from './routes/session.$sessionId'
import { Route as SettingsToolsNameRouteImport } from './routes/settings_.tools.$name'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionSessionIdRoute = SessionSessionIdRouteImport.update({
  id: '/session/$sessionId',
  path: '/session/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsToolsNameRoute = SettingsToolsNameRouteImport.update({
  id: '/settings_/tools/$name',
  path: '/settings/tools/$name',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/session/$sessionId': typeof SessionSessionIdRoute
  '/settings/tools/$name': typeof SettingsToolsNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/session/$sessionId': typeof SessionSessionIdRoute
  '/settings/tools/$name': typeof SettingsToolsNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/session/$sessionId': typeof SessionSessionIdRoute
  '/settings_/tools/$name': typeof SettingsToolsNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/settings' | '/session/$sessionId' | '/settings/tools/$name'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/settings' | '/session/$sessionId' | '/settings/tools/$name'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/session/$sessionId'
    | '/settings_/tools/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  SessionSessionIdRoute: typeof SessionSessionIdRoute
  SettingsToolsNameRoute: typeof SettingsToolsNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$sessionId': {
      id: '/session/$sessionId'
      path: '/session/$sessionId'
      fullPath: '/session/$sessionId'
      preLoaderRoute: typeof SessionSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings_/tools/$name': {
      id: '/settings_/tools/$name'
      path: '/settings/tools/$name'
      fullPath: '/settings/tools/$name'
      preLoaderRoute: typeof SettingsToolsNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  SessionSessionIdRoute: SessionSessionIdRoute,
  SettingsToolsNameRoute: SettingsToolsNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
