"""The UI-agnostic core of alpine-code.

A frontend creates a ``Session`` with an ``on_event`` callback and an ``Approver``, then awaits ``asend`` (or calls
``send`` without an event loop). Everything a frontend needs is exported here; frontends must not import alpineagents
or core submodules directly.
"""

from .agents import DEFAULT_ID as DEFAULT_AGENT
from .agents import LOOKS, AgentConfig, AgentList, free_character
from .approval import ApprovalRequest, Approver, AsyncApprover, BlockingApprover, Decision, blocked_reason
from .catalog import hidden_models, load_catalog
from .config import (
    ConfigError,
    Connection,
    Settings,
    config_file,
    remove_connection,
    save_connection,
    set_default_mode,
    set_default_model,
    set_review_model,
    show_model,
)
from .events import (
    AssistantDone,
    ContextCompacted,
    Event,
    Failed,
    Interrupted,
    Notice,
    RunFinished,
    StopReason,
    TextDelta,
    ToolFinished,
    ToolResultKind,
    ToolStarted,
    TurnStarted,
    UsageInfo,
)
from .git import CloneError, GitStatus, PullRequest, clone, current_branch, pull_request
from .git import status as git_status
from .home import home_dir
from .items import (
    AgentChanged,
    AgentMessage,
    AgentSwitched,
    ApprovalItem,
    Compaction,
    Deleted,
    InfoChanged,
    Item,
    ItemCompleted,
    ItemDelta,
    ItemDiscarded,
    ItemEvent,
    ItemRecorder,
    ItemStarted,
    NoticeItem,
    ReviewBlocked,
    RunStopped,
    StatusLine,
    ToolCallItem,
    UserMessage,
    event_from_dict,
    event_to_dict,
    item_from_dict,
    item_to_dict,
)
from .memory import Evidence, Memories, Memory, MemoryNotes, Refused, Scope, Suggestion
from .models import ModelListError, chatgpt_tokens, list_models
from .permissions import Mode
from .projects import Project, ProjectList
from .providers import PROVIDERS, Api, Auth, Billing, Provider
from .review import GlobalAgentsMd, ModelReviewer, Review, Reviewer, ReviewRequest, TrustedNote, TrustedSource
from .secrets import FileSecrets, Secrets
from .session import Session, Snapshot, delete_session, list_sessions
from .storage import (
    Activity,
    ActivityKind,
    FileSessionLog,
    SessionInfo,
    SessionLog,
    SessionStatus,
    Storage,
    file_storage,
)
from .tool_sources import Builtins, Offered, Origin, ToolSource, ToolSources, builtins_only, gather, pick
from .toolbox import (
    REVIEWED,
    Check,
    DraftError,
    PackageInfo,
    Param,
    TestResult,
    Toolbox,
    ToolboxError,
    ToolFile,
    ToolSummary,
    draft,
    package_info,
    summarize,
)
from .tools import BUILTIN, Workspace

__all__ = [
    "Session",
    "Evidence",
    "Memories",
    "Memory",
    "MemoryNotes",
    "Refused",
    "Scope",
    "Suggestion",
    "Snapshot",
    "list_sessions",
    "delete_session",
    "Storage",
    "SessionLog",
    "FileSessionLog",
    "Activity",
    "ActivityKind",
    "SessionInfo",
    "SessionStatus",
    "file_storage",
    "Settings",
    "ConfigError",
    "home_dir",
    "config_file",
    "Connection",
    "remove_connection",
    "save_connection",
    "set_default_mode",
    "set_default_model",
    "set_review_model",
    "blocked_reason",
    "show_model",
    "hidden_models",
    "load_catalog",
    "Provider",
    "PROVIDERS",
    "Api",
    "Auth",
    "Billing",
    "Secrets",
    "FileSecrets",
    "chatgpt_tokens",
    "list_models",
    "ModelListError",
    "Project",
    "ProjectList",
    "AgentConfig",
    "AgentList",
    "DEFAULT_AGENT",
    "LOOKS",
    "free_character",
    "Toolbox",
    "ToolboxError",
    "ToolFile",
    "ToolSummary",
    "Param",
    "Check",
    "DraftError",
    "PackageInfo",
    "TestResult",
    "BUILTIN",
    "REVIEWED",
    "Builtins",
    "Workspace",
    "Offered",
    "Origin",
    "ToolSource",
    "ToolSources",
    "builtins_only",
    "gather",
    "pick",
    "draft",
    "package_info",
    "summarize",
    "clone",
    "CloneError",
    "current_branch",
    "git_status",
    "GitStatus",
    "pull_request",
    "PullRequest",
    "Mode",
    "Reviewer",
    "ReviewRequest",
    "Review",
    "ModelReviewer",
    "TrustedSource",
    "TrustedNote",
    "GlobalAgentsMd",
    "Approver",
    "BlockingApprover",
    "AsyncApprover",
    "ApprovalRequest",
    "Decision",
    "Event",
    "TurnStarted",
    "TextDelta",
    "AssistantDone",
    "ToolStarted",
    "ToolFinished",
    "ToolResultKind",
    "ContextCompacted",
    "Notice",
    "RunFinished",
    "StopReason",
    "Interrupted",
    "Failed",
    "UsageInfo",
    "AgentMessage",
    "AgentSwitched",
    "AgentChanged",
    "ApprovalItem",
    "ReviewBlocked",
    "Compaction",
    "Deleted",
    "InfoChanged",
    "Item",
    "ItemCompleted",
    "ItemDelta",
    "ItemDiscarded",
    "ItemEvent",
    "ItemRecorder",
    "ItemStarted",
    "NoticeItem",
    "RunStopped",
    "StatusLine",
    "ToolCallItem",
    "UserMessage",
    "event_from_dict",
    "event_to_dict",
    "item_from_dict",
    "item_to_dict",
]
