"""The UI-agnostic core of alpine-code.

A frontend creates a ``Session`` with an ``on_event`` callback and an ``Approver``, then awaits ``asend`` (or calls
``send`` without an event loop). Everything a frontend needs is exported here; frontends must not import alpineagents
or core submodules directly.
"""

from .approval import ApprovalRequest, Approver, AsyncApprover, BlockingApprover, Decision
from .config import ConfigError, Connection, Settings, config_file, save_connection, set_default_model
from .events import (
    AssistantDone,
    ContextCompacted,
    Event,
    Failed,
    Interrupted,
    Notice,
    RunFinished,
    StopReason,
    TextDelta,
    ToolFinished,
    ToolResultKind,
    ToolStarted,
    TurnStarted,
    UsageInfo,
)
from .git import CloneError, GitStatus, PullRequest, clone, current_branch, pull_request
from .git import status as git_status
from .home import home_dir
from .items import (
    AgentMessage,
    ApprovalItem,
    Compaction,
    Deleted,
    InfoChanged,
    Item,
    ItemCompleted,
    ItemDelta,
    ItemDiscarded,
    ItemEvent,
    ItemRecorder,
    ItemStarted,
    NoticeItem,
    RunStopped,
    StatusLine,
    ToolCallItem,
    UserMessage,
    event_from_dict,
    event_to_dict,
    item_from_dict,
    item_to_dict,
)
from .models import ModelListError, chatgpt_tokens, list_models
from .permissions import Mode
from .projects import Project, ProjectList
from .providers import PROVIDERS, Api, Auth, Billing, Provider
from .secrets import FileSecrets, Secrets
from .session import Session, Snapshot, delete_session, list_sessions
from .storage import (
    Activity,
    ActivityKind,
    FileSessionLog,
    SessionInfo,
    SessionLog,
    SessionStatus,
    Storage,
    file_storage,
)

__all__ = [
    "Session",
    "Snapshot",
    "list_sessions",
    "delete_session",
    "Storage",
    "SessionLog",
    "FileSessionLog",
    "Activity",
    "ActivityKind",
    "SessionInfo",
    "SessionStatus",
    "file_storage",
    "Settings",
    "ConfigError",
    "home_dir",
    "config_file",
    "Connection",
    "save_connection",
    "set_default_model",
    "Provider",
    "PROVIDERS",
    "Api",
    "Auth",
    "Billing",
    "Secrets",
    "FileSecrets",
    "chatgpt_tokens",
    "list_models",
    "ModelListError",
    "Project",
    "ProjectList",
    "clone",
    "CloneError",
    "current_branch",
    "git_status",
    "GitStatus",
    "pull_request",
    "PullRequest",
    "Mode",
    "Approver",
    "BlockingApprover",
    "AsyncApprover",
    "ApprovalRequest",
    "Decision",
    "Event",
    "TurnStarted",
    "TextDelta",
    "AssistantDone",
    "ToolStarted",
    "ToolFinished",
    "ToolResultKind",
    "ContextCompacted",
    "Notice",
    "RunFinished",
    "StopReason",
    "Interrupted",
    "Failed",
    "UsageInfo",
    "AgentMessage",
    "ApprovalItem",
    "Compaction",
    "Deleted",
    "InfoChanged",
    "Item",
    "ItemCompleted",
    "ItemDelta",
    "ItemDiscarded",
    "ItemEvent",
    "ItemRecorder",
    "ItemStarted",
    "NoticeItem",
    "RunStopped",
    "StatusLine",
    "ToolCallItem",
    "UserMessage",
    "event_from_dict",
    "event_to_dict",
    "item_from_dict",
    "item_to_dict",
]
